#!/bin/bash

# 定义路径
PROJECT_ROOT="/home/cmx/codespace/Astra"
THIRD_PARTY_DIR="$PROJECT_ROOT/third-party"
OUTPUT_HEADER="$PROJECT_ROOT/core/third-party.h"

# 排除路径
EXCLUDE_DIRS=(
    "$PROJECT_ROOT/third-party/mimalloc"
)

# 清空旧文件（如果存在）
> "$OUTPUT_HEADER"

# 写入文件头
echo "#pragma once" >> "$OUTPUT_HEADER"
echo "// Auto-generated by generate_third_pch.bash" >> "$OUTPUT_HEADER"
echo "// DO NOT edit manually!" >> "$OUTPUT_HEADER"
echo "" >> "$OUTPUT_HEADER"

# 构建 find 命令参数
find_cmd=(find "$THIRD_PARTY_DIR" -type f)

# 添加排除参数
for dir in "${EXCLUDE_DIRS[@]}"; do
    find_cmd+=(! -path "$dir/*")
done

# 添加查找后缀名
find_cmd+=( \( -name "*.h" -o -name "*.hpp" \) )

# 执行 find 并写入 include
"${find_cmd[@]}" | while read -r file; do
    include_path=${file#"$THIRD_PARTY_DIR/"}
    echo "#include \"$include_path\"" >> "$OUTPUT_HEADER"
done

# 执行一次format.sh
bash format.sh 2>&1 | tee /dev/tty
echo "Running clang-tidy..."