name: Package

on:
  push:
    branches: [main, master]
    tags: ["v*"]
  pull_request:
    branches: [main, master]

jobs:
  package:
    name: Package for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, windows-2022]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Install dependencies (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake rpm dpkg
        timeout-minutes: 5

      - name: Install NSIS (Windows)
        if: runner.os == 'Windows'
        run: |
          choco install nsis
        timeout-minutes: 5

      - name: Configure CMake
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release --log-level=VERBOSE
        timeout-minutes: 10

      - name: Build
        run: |
          cmake --build build --config Release --verbose
        timeout-minutes: 20

      - name: Package (with libs)
        run: |
          cd build
          cpack -C applications
        timeout-minutes: 10

      - name: List generated packages (with libs)
        run: |
          ls -la build/
        shell: bash

      - name: Upload artifacts (with libs)
        uses: actions/upload-artifact@v4
        with:
          name: astra-cache-server-${{ matrix.os }}-with-libs
          path: |
            build/*.tar.gz
            build/*.zip
            build/*.deb
            build/*.rpm
            build/*.exe

  release:
    name: Create Release
    needs: [package]
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: Display structure of downloaded files
        run: ls -R

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            astra-cache-server-*/*.tar.gz
            astra-cache-server-*/*.zip
            astra-cache-server-*/*.deb
            astra-cache-server-*/*.rpm
            astra-cache-server-*/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
